### ISSUE TITLE
Sales Return: Cannot create sales return for Batch item

### ISSUE THREAD

**Issue by mujeerhashmi** [yrestom/POS-Awesome#62]
### Versions

erpnext 13.6.0
frappe 13.6.0
posawesome 2.0.1

### Stacktrace / full error message

```
libs.min.js?ver=1625534093.0:228 TypeError: Cannot read property 'batch_qty' of undefined
    at a.set_batch_qty (Invoice.vue?rollup-plugin-vue=script.js:1410)
    at Invoice.vue?rollup-plugin-vue=script.js:869
    at Array.forEach (<anonymous>)
    at a.new_invoice (Invoice.vue?rollup-plugin-vue=script.js:864)
    at wn.<anonymous> (Invoice.vue?rollup-plugin-vue=script.js:2166)
    at He (libs.min.js?ver=1625534093.0:228)
    at wn.e.$emit (libs.min.js?ver=1625534093.0:228)
    at a.submit_dialog (Returns.vue?rollup-plugin-vue=script.js:145)
    at He (libs.min.js?ver=1625534093.0:228)
    at a.n (libs.min.js?ver=1625534093.0:228)

libs.min.js?ver=1625534093.0:228 TypeError: Cannot create property 'posa_delivery_date' on string ''
    at wn.<anonymous> (Payments.vue?rollup-plugin-vue=script.js:914)
    at He (libs.min.js?ver=1625534093.0:228)
    at wn.e.$emit (libs.min.js?ver=1625534093.0:228)
    at a.invoiceType (Invoice.vue?rollup-plugin-vue=script.js:2210)
    at fn.run (libs.min.js?ver=1625534093.0:228)
    at un (libs.min.js?ver=1625534093.0:228)
    at Array.<anonymous> (libs.min.js?ver=1625534093.0:228)
    at qe (libs.min.js?ver=1625534093.0:228)
```

### Steps to reproduce

1. Create a Sales Invoice for an Item with Batch No.
2. Create Sales Invoice Return for the invoice generated in the previous step
3. The Customer is not reloaded & the screenshot of the browser console is attached.

### What is Expected?
The Sales Invoice return should be possible.

### What is actually happening?
I am getting a pop-up `There is no customer` upon click of `Pay` for sales invoice return. The customer field is non-clickable.

### Screenshots
![POSAwesome_SalesReturn_BatchItem](https://user-images.githubusercontent.com/12420747/124539710-9b027b80-de3b-11eb-92bb-5cb8f4538693.png)

**Comment by mujeerhashmi** [comment]
@yrestom thank you for such a nice contribution. I am planning to use this for a hospital pharmacy. WIll keep reporting issues and feature requests :). I am not a Vue developer. As such, I won't be able to send any PRs but can only test & raise issues. Please bear with me.

**Comment by yrestom** [comment]
@mujeerhashmi 
I will work on it soon
Thank you

**Comment by yrestom** [comment]
@mujeerhashmi 
I couldn't reproduce the error
Is there another error log in the system or any additional information that can help

**Comment by lamphanjk** [comment]
I have the same issue with item with batch number

**Comment by yrestom** [comment]
@lamphanjk Can you please give more details that can help to reproduce the error, and then I can fix it

**Comment by lamphanjk** [comment]
Please see the reproduce video as link:
https://phannguyenlam.tinytake.com/msc/NjI3OTYzNl8xODYyMzkzNA
@yrestom

**Comment by yrestom** [comment]
I think it should be fixed by this commit https://github.com/yrestom/POS-Awesome/commit/f6d4d5afa1ad971cce5091a58573628b7320928a

**Comment by lamphanjk** [comment]
Hi @yrestom , I still have the same problem with the issue, the commit you mention is merged? I use the lastest version 3.1.0
