### ISSUE TITLE
[BUG]: Cart Available QTY shows Stock from Item Default Warehouse and not POS Profile Warehouse

### ISSUE THREAD

**Issue by dmbabu** [yrestom/POS-Awesome#75]
### Versions

ERPNext: v13.11.1 (version-13)
Frappe Framework: v13.11.0 (version-13)
POS Awesome: v3.0.1 (master)

### Steps to reproduce

1. Create Two or more Warehouses (assumes they are in different locations e.g. Main Warehouse and Outlet Warehouse)
2. Create Item, add default Warehouse (any created in step 1 above) to Item Defaults
3. Add Stock of Item (created in step 2) to each Warehouse (created in step 1)
4. Create POS Awesome profile with any Warehouse (created in step 1)
3. Launch POS Awesome and add Item to cart

### What is Expected?
For Item with stock in multiple warehouses, POS Awesome should show Available QTY from Warehouse defined in POS Profile for both Item List (left hand side) and Cart (right hand side). 

### What is actually happening?
Available QTY in Item list shows correct value (Item stock in POS Profile-defined warehouse). Available QTY in cart Item shows stock available in Item's default Warehouse (defined in Item master). POS Awesome Item in cart seems to pick stocks available in Item's default warehouse and not warehouse defined in POS Profile

### Additional context
Item cart Avaiable QTY seems to load with correct value then quickly refreshes/updates to incorrect value.

### Screenshot
![e1-s1](https://user-images.githubusercontent.com/45001106/135742939-9373943c-484d-4925-afad-fa290e13b0cb.png)
![e1-s2](https://user-images.githubusercontent.com/45001106/135742943-55b483b6-75a4-4f53-9412-73c579f6711d.png)
s

**Comment by yrestom** [comment]
Please use the issue guideline https://github.com/frappe/erpnext/wiki/Issue-Guidelines

**Comment by yrestom** [comment]
Thank you, I fixed here https://github.com/yrestom/POS-Awesome/commit/97e33ee6733bee45860289b7bbed353675acb378

**Comment by immueke** [comment]
> Please use the issue guideline https://github.com/frappe/erpnext/wiki/Issue-Guidelines

I am still experiencing this issue with awesome POS. I am not able to view stock in a child warehouses.

**Comment by yrestom** [comment]
> > Please use the issue guideline https://github.com/frappe/erpnext/wiki/Issue-Guidelines
> 
> I am still experiencing this issue with awesome POS. I am not able to view stock in a child warehouses.

Please open a new issue with the relevant info
